import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/ui/header';
import Footer from '@/components/ui/footer';
import PhoneFrame from '@/components/ui/phoneframe';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <Header />

                <main className="border-2 border-t-1 border-b-1 p-3 overflow-hidden overflow-y-auto">
                    {/* <PhoneFrame>{children}</PhoneFrame> */}
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
